const mongoose = require('mongoose');

const PriceSchema = new mongoose.Schema({
  USD: { type: Number, required: true },
  EUR: Number,
  INR: Number,
  original: { type: Number } // Original price for discount display (in USD typically)
}, { _id: false });

const SizeSchema = new mongoose.Schema({
  height: Number,
  width: Number,
  unit: { type: String, default: 'cm' }
}, { _id: false });

const PaintingSchema = new mongoose.Schema({
  title: { type: String, required: true },
  artistId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  artistName: String,
  artistCountry: String,
  sku: String,
  slug: String,
  year: Number,
  editionType: { type: String, enum: ['Original','Limited Edition','Open Edition'] },
  editionNumber: String,
  category: String,
  subcategory: String,
  style: String,
  subject: String,
  description: String,
  size: SizeSchema,
  medium: String,
  surface: String,
  technique: String,
  orientation: { type: String, enum: ['Portrait','Landscape','Square'], default: 'Portrait' },
  colorPalette: [String],
  mood: String,
  weightKg: Number,
  sizeCategory: { type: String, enum: ['Small','Medium','Large','Oversized'] },
  fragilityLevel: { type: String, enum: ['Low','Medium','High'] },
  price: PriceSchema,
  currency: { type: String, enum: ['USD','EUR','GBP','INR'], default: 'USD' },
  taxIncluded: { type: Boolean, default: false },
  vatPercent: Number,
  customsDeclaredValue: Number,
  commissionPercent: Number,
  artistPayoutAmount: Number,
  stock: { type: Number, default: 1 },
  reservedStock: { type: Number, default: 0 },
  allowBackorder: { type: Boolean, default: false },
  maxPurchaseQty: { type: Number, default: 1 },
  images: [String],
  imageAltText: String,
  imageCopyrightOwner: String,
  framed: { type: Boolean, default: false },
  frameMaterial: String,
  frameColor: String,
  frameIncludedInPrice: { type: Boolean, default: false },
  isCustomizable: { type: Boolean, default: false },
  protectiveCoating: String,
  glassType: String,
  certificateOfAuthenticity: { type: Boolean, default: false },
  certificateId: String,
  signedByArtist: { type: String, enum: ['Front','Back','No'], default: 'No' },
  signatureLocation: String,
  copyrightHolder: String,
  reproductionRights: { type: String, enum: ['Allowed','Not Allowed'], default: 'Not Allowed' },
  resaleRights: { type: Boolean, default: false },
  artistRoyaltyOnResalePercent: Number,
  copyrightYear: Number,
  shippingOriginCountry: String,
  shipsFromCity: String,
  processingDays: Number,
  internationalShipping: { type: Boolean, default: true },
  supportedCountries: [String],
  hsCode: String,
  packagingType: { type: String, enum: ['Tube','Box','Crate'] },
  insuranceAvailable: { type: Boolean, default: true },
  insuranceValue: Number,
  handlingFee: Number,
  exportDocumentationRequired: { type: Boolean, default: false },
  returnAllowed: { type: Boolean, default: true },
  returnWindowDays: Number,
  refundMethod: { type: String, enum: ['Original','Manual'], default: 'Original' },
  damageClaimAllowed: { type: Boolean, default: true },
  damageClaimWindowDays: Number,
  returnShippingPaidBy: { type: String, enum: ['Buyer','Seller'], default: 'Buyer' },
  restockingFeePercent: Number,
  metaTitle: String,
  metaDescription: String,
  seoKeywords: [String],
  tags: [String],
  collectionName: String,
  homepagePriorityRank: Number,
  socialShareImage: String,
  countryOfOriginLabel: String,
  artistBioVerified: { type: Boolean, default: false },
  artworkCondition: { type: String, default: 'New' },
  culturalPropertyDeclaration: String,
  citesCompliance: String,
  viewCount: { type: Number, default: 0 },
  wishlistCount: { type: Number, default: 0 },
  addToCartCount: { type: Number, default: 0 },
  conversionRate: Number,
  lastViewedDate: Date,
  popularityScore: { type: Number, default: 0 },
  internalNotes: String,
  qualityCheckStatus: String,
  approvalStatus: { type: String, enum: ['Pending','Approved','Rejected'], default: 'Approved' },
  visible: { type: Boolean, default: true },
  fraudRiskFlag: { type: Boolean, default: false },
  manualPriceOverride: Number,
  emergencyDisableListing: { type: Boolean, default: false },
  arView: { type: Boolean, default: false },
  wallColorPreview: { type: Boolean, default: false },
  sizeComparisonTool: { type: Boolean, default: false },
  nftLink: String,
  blockchainCertificateHash: String,
  averageRating: { type: Number, default: 0 },
  ratingsCount: { type: Number, default: 0 },
  status: { type: String, enum: ['available','sold'], default: 'available' },
  featured: { type: Boolean, default: false }
}, { timestamps: true });

const Painting = mongoose.models.Painting || mongoose.model('Painting', PaintingSchema);
module.exports = { Painting };
